### ISSUE TITLE
Unable to Complete VM Startup

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#32]
Hello,

I'm trying to install QVD on my system to test out. I have have a few hiccups, but now I think I am so close, but still can't get the VM started. The node is running, DI created, and assigned a user to the image. When I go to start the VM it will say "starting" for a long time, then will go back to "stopped".

I think these lines has meaning, but not sure how to fix:  2016/02/06 09:56:11 19315 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 316 - vma_monitor_failed for vm '3', tries: 37/40

I have tried Ubuntu and OpenSUSU images from the website.

Here is the log file:

[qvd.log.txt](https://github.com/theqvd/theqvd/files/120335/qvd.log.txt)

**Comment by nitomartinez** [comment]
Hi,

thanks for trying QVD.

Ot seems that you are using the LXC image instead of the QCOW one with KVM virtualization. The main difference is if you use full virtualization with KVM, or containers with LXC.

{code}
2016/02/06 09:26:12 19315 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 302 - Running command ['qemu-img','create','-f','qcow2','-b','/var/lib/qvd/storage/images/1-opensuse-12.3-qvd.tar.gz','/var/lib/qvd/storage/overlays/1-1-overlay.qcow2']
{code}


I see two Option to fix this:
**
1) download a KVM image (QCOW format). And use that**

You can download it from here:

http://theqvd.com/product/download

Look for "QVD Demonstration DI (openSUSE 12.3 – Xfce Desktop for KVM) [1.6GB]"

**2) Change the settings to use LXC containers. See**

http://docs.theqvd.com/docs/AdministrationManual.html#_qvd_base_configuration

mainly this:

{code}
# qa config set vm.hypervisor=lxc
# qa config set vm.lxc.unionfs.bind.ro=0
# qa config set vm.lxc.unionfs.type=unionfs-fuse
# qa config set command.unionfs-fuse=/usr/bin/unionfs
{code}

And then restart the server:

{code}
/etc/init.d/qvd-hkd restart
{code}

Please let us know if this helped,

**Comment by ryananderson0219** [comment]
THANK YOU!!!!!

I got it running and logged in with your help! - KVM
Now I got to work on LXC since I believe it is more efficient from my understanding from the documentation. But that look simple now too by your help above. I want to ask though - I have to run one or the other (KVM/LXC), can't run both, correct?

**Comment by nitomartinez** [comment]
:-)

Glad to see it worked, thanks for trying it out.


Regarding your question, the version you got only supports one or the other, that is LXC or KVM.


But stay tuned there are changes in the upcoming version ;-)
