### ISSUE TITLE
QVD-Admin/bin/qvd-admin.pl: Configuration entry for database.password missing

### ISSUE THREAD

**Issue by HenrikBach1** [theqvd/theqvd#47]
Hi,

I'm trying to follow your QVD Installation Guide, Chapter 4.

However, when trying to issue the command (from section 4.1):

"----------------------
theqvd-master/ext# perl -Mperlrc=. -Mlib::glob=*/lib QVD-Admin/bin/qvd-admin.pl 
Configuration entry for database.password missing
Compilation failed in require at /usr/local/share/perl/5.22.1/QVD/DB/Simple.pm line 6.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.22.1/QVD/DB/Simple.pm line 6.
Compilation failed in require at QVD-Admin/lib/QVD/Admin.pm line 12.
BEGIN failed--compilation aborted at QVD-Admin/lib/QVD/Admin.pm line 12.
Compilation failed in require at QVD-Admin/lib/QVD/AdminCLI.pm line 8.
BEGIN failed--compilation aborted at QVD-Admin/lib/QVD/AdminCLI.pm line 8.
Compilation failed in require at QVD-Admin/bin/qvd-admin.pl line 9.
BEGIN failed--compilation aborted at QVD-Admin/bin/qvd-admin.pl line 9.
root@sad-B551LA:/home/sad/Downloads/theqvd-master/ext# ls -al /etc/qvd/
total 16
drwxr-xr-x   2 root root  4096 Dec 22 13:37 .
drwxr-xr-x 132 root root 12288 Dec 22 08:22 ..
-----------------------"

it fails.

What am I doing wrong (sorry for the newbie perl and other questions)?

/Henrik

**Comment by vatral** [comment]
Hello,

First of all, what are you trying to accomplish? If you want to simply get QVD running, using the packages would be easier. If you want to install them on an unsupported distribution, you can try with alien (a package format conversion tool). Our packages are not complicated and self-contained, so this should work.

That said, it seems that you're trying to run qvd-admin too early. See section 4.5 which explains how to create the configuration file that qvd-admin wants to work correctly. Once you do that, your error should go away.

**Comment by HenrikBach1** [comment]
Hi,

First of all, sorry for the confusion on my approach to get into this project. 

What I'm trying to accomplish is: I don't want to run pre-build packages or demo, even on a supported platform per experience from other FLOSS projects, I've been participating in, before I can make and run them on my own. If not, then it makes no sense to me to use and/or participate in building and extending. 

With this in mind, I'm first trying to configure and run (with perl directly from the source tree as suggested in other comments) the QVD system on a single machine from source tree.

Later I'll try to run components dispersed and distributed on more machines, and continue with building, especially _testing_, and installing the modules.

The first section 4.1 is (then) written, at least to me, in wrong order. Because the documentation starts with a pre-liminary explanation of that tool of what it does, and how to issue it.

However, I first started with ignoring item 2. and continued with installing and configuring the database. but then at section 4.6 I tried to issue the command:

"---------------------------
perl -Mperlrc=. -Mlib::glob=*/lib QVD-DB/bin/qvd-deploy-db.pl
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=qvddb;host=sad-B551LA;connect_timeout=20','qvd',...) failed: could not connect to server: Connection refused
	Is the server running on host "sad-B551LA" (127.0.1.1) and accepting
	TCP/IP connections on port 5432? at /usr/local/share/perl/5.22.1/DBIx/Class/Storage/DBI.pm line 1517.
 at /usr/local/share/perl/5.22.1/DBIx/Class/Storage.pm line 113. at /usr/local/share/perl/5.22.1/QVD/DB.pm line 85
---------------------------"

Then, I thought, that I maybe was missing something from start, because, the documentation started with this command and it maybe could clarify things for me.

Moreover, the documentation starts with installing and configuring the QVD Node server from Chapter 5. But, how can a deployment of tables on a database be dependent on a running QVD Node server? 

So, I'm unfortunately confused at this point. That is why I'm asking for help for what to do when tools fails and I'm a newbie in this field.

Thank you for your patience and help.

/Henrik

**Comment by vatral** [comment]
Hello,

Alright, fair enough. I just wanted to make sure you weren't making things more complicated than they have to be. We don't have documentation targeted towards people doing everything from scratch right now, but I have no problem with explaining things.

The message you got indicates the script was unable to connect to the database on host  "sad-B551LA", port 5432. Now there are a few likely problems here:

First of all, I'm noticing that sad-B551LA resolves to 127.0.**1**.1. On many distributions, PostreSQL by default runs on localhost, which is 127.0.**0**.1. Despite both being loopback addresses, they're still independent, so a service running on 127.0.0.1 won't answer to connections to 127.0.1.1.

So that seems to be the most likely problem: You should either tell PostgreSQL to run on 127.0.1.1, by editing postgresql.conf and changing the listen_addresses setting. Or you could change the database host to a hostname that resolves to 127.0.0.1 instead. 

Another possible problem is that PostgreSQL is not running, or only listening on UNIX sockets.


By the way, which distribution and which version are you running?

**Comment by HenrikBach1** [comment]
Hi,

Thank you for your clarifications. It turned out, that it was an misconfiguration in my postgresql.conf file, that made postgresql not to listen on all local ip's as suggested in the documentation.

Tables are now deployed in the database.

/Henrik
