### ISSUE TITLE
Windows client printing

### ISSUE THREAD

**Issue by bardicrune** [theqvd/theqvd#64]
We are unable to get printer redirection working.  File redirection is working properly, but printers local to the Win10 x64 test PC are not showing up in the CUPS server on the linux vm.  This is occurring when using the 4.0 OVA image and with the hosted Demo versions.  We are using the 3.5 version of the windows client listed on the download page.  We have also tried the qvdclient_i686-pc-cygwin.exe binary.

Edit:  Audio redirection is also not working.

We are looking for a product that can replace a traditional Windows Terminal Server for a Java application that runs just as well on linux.  But functional printer redirection is a major requirement.

**Comment by jzeaherra** [comment]
Hi, we need some information. In your Windows client machine, go to your user's appdata/roaming directory (you can get there quickly by going to start->run and entering %appdata%). You will find QVD data directory inside. 
Send us qvd-client.log and client.conf files please.

**Comment by nicolasarenas** [comment]
@bardicrune why are you using 3.5 version of the client? Did you try with the 4.0.0 version? . In the other hand, the binary version of the client do not have the printer redirection capability. 

Keep in mind that you will need to install the printer Linux drivers for the specific printer (or printers) you plan to use in the virtual machine image (DI). Which could not be installed in the images. 

We are reworking the printing subsystem for the Windows client in a way that would remove the need for installing the printer drivers on the VM image. We have already done most of the development and we are now in the integration stage.

Anyway, please sent us the logs as requested by @jzeaherra, that way we can take a deeper look into your problem. 

PS: do you know it is possible to configure QVD to serve just your Java application instead of a full desktop?

**Comment by nicolasarenas** [comment]
@bardicrune, it seems that in our web page the 4.0 version appears as coming soon, we are fixing that, in the meantime, you can get it from [here](http://theqvd.com/downloads/windows/qvd-client-setup-4.0.0.exe)

Regards.

**Comment by jzeaherra** [comment]
Also, while we work on our new printing system, you can use a workaround for printing tests:

1. Go to Start and look for "manage advanced sharing settings".
2. Make sure in your "current profile", that file and printer sharing is on.
3. Under "all networks", turn off password protected sharing at the bottom.

Please, bear in mind this will share your printers with all of your network anonymously ( meaning all users in your network will see your network shared printers and use them as they please without any authentication ... ). It will also make your network shared printers available to the QVD Virtual Machine, which is what we're looking for here. 

As you see, not a production-ready configuration, and only for testing purposes... but it'll make a workaround while we finish our new printing system.

By the way, the network sharing name for the printers you want to test can't have spaces in their names ( this is related to another recently discovered bug for which we're about to release a patched version ).

Also, please don't forget about the logs and config I asked you for, so that we can look into your sound issue too.

Regards.

**Comment by bardicrune** [comment]
Sorry for the delay in response, here are the attached 3.5 client files

[QVD-client-3.5.zip](https://github.com/theqvd/theqvd/files/1058202/QVD-client-3.5.zip)


.

**Comment by bardicrune** [comment]
With the 4.0 client connecting to hosted Demo version:
[QVD-client-4.0-demo.zip](https://github.com/theqvd/theqvd/files/1058372/QVD-client-4.0-demo.zip)
Audio and File redirection work, but not printers.  This is both before and after turning off "password protected sharing" as suggested by jzeaherra ("file and printer sharing" is already enabled) .

The 4.0 client will not connect to the 4.0 OVA at all.
When Server is set to "localhost":
[QVD-client-4.0-lh.zip](https://github.com/theqvd/theqvd/files/1058378/QVD-client-4.0-lh.zip)
![lh](https://user-images.githubusercontent.com/29209096/26884656-e4fb891a-4b65-11e7-8b45-1120a67ab1f9.png)

When Server is set to "127.0.0.1":
[QVD-client-4.0-ip.zip](https://github.com/theqvd/theqvd/files/1058384/QVD-client-4.0-ip.zip)
![ip](https://user-images.githubusercontent.com/29209096/26884764-379ad662-4b66-11e7-9877-18ecbe781d69.png)

**Comment by jzeaherra** [comment]
Yes you're right! The certificate the ova is presenting is not what it should, so you won't be able to connect. We have to fix it, thanks for the catch.

Please, go on testing with our hosted demo. For the printing, are you sharing the printer? Disabling password protected sharing is not enough, your printer must be shared with the network, and as I mentioned before, it has to be shared with a name not containing spaces.

If your configuration is already that way, we would need to check the vma logs (these are the logs inside the VM at our demo). You will find them inside the virtual machine, at /var/log , everything that starts with qvd- .

Shared folders are a great way to get these logs by the way :)

Regards,
Juan

**Comment by bardicrune** [comment]
I verified that I have an HP LaserJet M402dn setup as a shared printer on my Windows PC shared as "Printer5".  I have attached the qvd-* logs from /var/log of the VM.
[temp1.zip](https://github.com/theqvd/theqvd/files/1061110/temp1.zip)

**Comment by jzeaherra** [comment]
Hi. The error you're getting can happen when you connect to a just-started vm. There is a race condition between the qvd client connection and the vm cups service availability. 

Please reconnect to the same vm a second time and you should see your printers there.

**Comment by bardicrune** [comment]
I reconnected to the VM after a logout and then after a shutdown and still did not have my printers available.  
[qvd-logs.zip](https://github.com/theqvd/theqvd/files/1068631/qvd-logs.zip)

**Comment by jzeaherra** [comment]
Seeing your logs, it seems like the vm is correctly connecting to Windows via samba, and asking for the printers. And your windows shows no shared printers... Do you have any printing software, antivirus or firewall that may be blocking access to your printer?
For testing purposes, can other pc in your network see and use your printer?

**Comment by bardicrune** [comment]
Yes, other devices on the network can see and print to this shared printer.

**Comment by jzeaherra** [comment]
I've been trying to reproduce your problem. When adding the printer to windows 10, it kind of tricked me... When you add a printer, you first select the printer and then, it asks if you want to share the printer with your network, and what name should it be shared by... You can give it a short name, but if you go to the printer properties afterwards, that name you gave it, is just the "location" parameter. The share name is still the long printer name with spaces... I had to manually change it in the sharing tab before it can be seen from QVD. 
Could you please double check that name? That would be in the printer properties, "Sharing" tab, "Share name" parameter. That mustn't have any spaces.

**Comment by bardicrune** [comment]
Printer5 is the share name.  It was shared initially using the "sharing" tab.

**Comment by bardicrune** [comment]
Found the issue.  Double-checked all settings and "password protected sharing" had become re-enabled.  The printer is now showing up in the session.

Is there an ETA on the other printing method?  As we are testing this product for use in the medical industry, having unsecured shares on PC's violates data protection policies.  Also the requirement to share every printer that the user want's to print to from the remote session will be a nightmare to administer.

**Comment by jzeaherra** [comment]
I've handed your question over to the right person, and you'll be contacted.

Regards,
Juan

**Comment by jzeaherra** [comment]
Hi! I've received news. 
The new printing driver is in the current year's roadmap, and we expect to have it available within the next five months. 
We're also very interested in your project and would like to have a conference call with you to see if we can be of any help. 
Please contact Nicolas Arenas ( nicolas.arenas[AT]qindel.com ) if you're interested.
Regards,
Juan

**Comment by jzeaherra** [comment]
Hi again,
 Do you need further help? May I close this issue?
